apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backups
  namespace: prod
  labels:
    app: taskhub
    component: postgres-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path