apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backups
  namespace: dev
  labels:
    app: taskhub
    component: postgres-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path